package com.tj.bet.dao;

import com.tj.bet.domain.BetRecd;
import com.tj.bet.domain.BetRecdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BetRecdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    long countByExample(BetRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    int deleteByExample(BetRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    int insert(BetRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    int insertSelective(BetRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    List<BetRecd> selectByExampleWithRowbounds(BetRecdExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    List<BetRecd> selectByExample(BetRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    BetRecd selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BetRecd record, @Param("example") BetRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BetRecd record, @Param("example") BetRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BetRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bet_recd
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BetRecd record);
}