package com.tj.bet.dao;

import com.tj.bet.domain.DiveRule;
import com.tj.bet.domain.DiveRuleExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface DiveRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    long countByExample(DiveRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    int deleteByExample(DiveRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    int insert(DiveRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    int insertSelective(DiveRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    List<DiveRule> selectByExampleWithRowbounds(DiveRuleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    List<DiveRule> selectByExample(DiveRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    DiveRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DiveRule record, @Param("example") DiveRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DiveRule record, @Param("example") DiveRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DiveRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DiveRule record);
}