package com.tj.bet.dao;

import com.tj.bet.domain.RaceRebateInfo;
import com.tj.bet.domain.RaceRebateInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface RaceRebateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    long countByExample(RaceRebateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    int deleteByExample(RaceRebateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    int insert(RaceRebateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    int insertSelective(RaceRebateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    List<RaceRebateInfo> selectByExampleWithRowbounds(RaceRebateInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    List<RaceRebateInfo> selectByExample(RaceRebateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    RaceRebateInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RaceRebateInfo record, @Param("example") RaceRebateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RaceRebateInfo record, @Param("example") RaceRebateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RaceRebateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RaceRebateInfo record);
}