package com.tj.bet.dao;

import com.tj.bet.domain.RebateRecd;
import com.tj.bet.domain.RebateRecdExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface RebateRecdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    long countByExample(RebateRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    int deleteByExample(RebateRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    int insert(RebateRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    int insertSelective(RebateRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    List<RebateRecd> selectByExampleWithRowbounds(RebateRecdExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    List<RebateRecd> selectByExample(RebateRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    RebateRecd selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RebateRecd record, @Param("example") RebateRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RebateRecd record, @Param("example") RebateRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RebateRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RebateRecd record);
}