spring:
  application:
    name: tj-registry
server:
  port: 9000
eureka:
  instance:
    prefer-ip-address: true
    instance-id: tj-registry
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka/

debug: false
management:
  endpoints:
    web:
      exposure:
        include: ["*"]