package com.tj.user.dao;

import com.tj.user.domain.UserAdmin;
import com.tj.user.domain.UserAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    long countByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    int deleteByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    int insert(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    int insertSelective(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    List<UserAdmin> selectByExampleWithRowbounds(UserAdminExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    List<UserAdmin> selectByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    UserAdmin selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserAdmin record, @Param("example") UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserAdmin record, @Param("example") UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserAdmin record);
}