package com.tj.event.domain;

import java.io.Serializable;

public class CategoryMapping implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_mapping.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_mapping.simple_full_category
     *
     * @mbg.generated
     */
    private String simpleFullCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_mapping.simple_short_category
     *
     * @mbg.generated
     */
    private String simpleShortCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_mapping.complex_full_category
     *
     * @mbg.generated
     */
    private String complexFullCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_mapping.complex_short_category
     *
     * @mbg.generated
     */
    private String complexShortCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_mapping.english_full_category
     *
     * @mbg.generated
     */
    private String englishFullCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_mapping.english_short_category
     *
     * @mbg.generated
     */
    private String englishShortCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_mapping.id
     *
     * @return the value of t_category_mapping.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_mapping.id
     *
     * @param id the value for t_category_mapping.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_mapping.simple_full_category
     *
     * @return the value of t_category_mapping.simple_full_category
     *
     * @mbg.generated
     */
    public String getSimpleFullCategory() {
        return simpleFullCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_mapping.simple_full_category
     *
     * @param simpleFullCategory the value for t_category_mapping.simple_full_category
     *
     * @mbg.generated
     */
    public void setSimpleFullCategory(String simpleFullCategory) {
        this.simpleFullCategory = simpleFullCategory == null ? null : simpleFullCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_mapping.simple_short_category
     *
     * @return the value of t_category_mapping.simple_short_category
     *
     * @mbg.generated
     */
    public String getSimpleShortCategory() {
        return simpleShortCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_mapping.simple_short_category
     *
     * @param simpleShortCategory the value for t_category_mapping.simple_short_category
     *
     * @mbg.generated
     */
    public void setSimpleShortCategory(String simpleShortCategory) {
        this.simpleShortCategory = simpleShortCategory == null ? null : simpleShortCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_mapping.complex_full_category
     *
     * @return the value of t_category_mapping.complex_full_category
     *
     * @mbg.generated
     */
    public String getComplexFullCategory() {
        return complexFullCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_mapping.complex_full_category
     *
     * @param complexFullCategory the value for t_category_mapping.complex_full_category
     *
     * @mbg.generated
     */
    public void setComplexFullCategory(String complexFullCategory) {
        this.complexFullCategory = complexFullCategory == null ? null : complexFullCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_mapping.complex_short_category
     *
     * @return the value of t_category_mapping.complex_short_category
     *
     * @mbg.generated
     */
    public String getComplexShortCategory() {
        return complexShortCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_mapping.complex_short_category
     *
     * @param complexShortCategory the value for t_category_mapping.complex_short_category
     *
     * @mbg.generated
     */
    public void setComplexShortCategory(String complexShortCategory) {
        this.complexShortCategory = complexShortCategory == null ? null : complexShortCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_mapping.english_full_category
     *
     * @return the value of t_category_mapping.english_full_category
     *
     * @mbg.generated
     */
    public String getEnglishFullCategory() {
        return englishFullCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_mapping.english_full_category
     *
     * @param englishFullCategory the value for t_category_mapping.english_full_category
     *
     * @mbg.generated
     */
    public void setEnglishFullCategory(String englishFullCategory) {
        this.englishFullCategory = englishFullCategory == null ? null : englishFullCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_mapping.english_short_category
     *
     * @return the value of t_category_mapping.english_short_category
     *
     * @mbg.generated
     */
    public String getEnglishShortCategory() {
        return englishShortCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_mapping.english_short_category
     *
     * @param englishShortCategory the value for t_category_mapping.english_short_category
     *
     * @mbg.generated
     */
    public void setEnglishShortCategory(String englishShortCategory) {
        this.englishShortCategory = englishShortCategory == null ? null : englishShortCategory.trim();
    }
}