package com.tj.event.domain;

import java.util.ArrayList;
import java.util.List;

public class CategoryMappingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public CategoryMappingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryIsNull() {
            addCriterion("simple_full_category is null");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryIsNotNull() {
            addCriterion("simple_full_category is not null");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryEqualTo(String value) {
            addCriterion("simple_full_category =", value, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryNotEqualTo(String value) {
            addCriterion("simple_full_category <>", value, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryGreaterThan(String value) {
            addCriterion("simple_full_category >", value, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("simple_full_category >=", value, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryLessThan(String value) {
            addCriterion("simple_full_category <", value, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryLessThanOrEqualTo(String value) {
            addCriterion("simple_full_category <=", value, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryLike(String value) {
            addCriterion("simple_full_category like", value, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryNotLike(String value) {
            addCriterion("simple_full_category not like", value, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryIn(List<String> values) {
            addCriterion("simple_full_category in", values, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryNotIn(List<String> values) {
            addCriterion("simple_full_category not in", values, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryBetween(String value1, String value2) {
            addCriterion("simple_full_category between", value1, value2, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryNotBetween(String value1, String value2) {
            addCriterion("simple_full_category not between", value1, value2, "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryIsNull() {
            addCriterion("simple_short_category is null");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryIsNotNull() {
            addCriterion("simple_short_category is not null");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryEqualTo(String value) {
            addCriterion("simple_short_category =", value, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryNotEqualTo(String value) {
            addCriterion("simple_short_category <>", value, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryGreaterThan(String value) {
            addCriterion("simple_short_category >", value, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("simple_short_category >=", value, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryLessThan(String value) {
            addCriterion("simple_short_category <", value, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryLessThanOrEqualTo(String value) {
            addCriterion("simple_short_category <=", value, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryLike(String value) {
            addCriterion("simple_short_category like", value, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryNotLike(String value) {
            addCriterion("simple_short_category not like", value, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryIn(List<String> values) {
            addCriterion("simple_short_category in", values, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryNotIn(List<String> values) {
            addCriterion("simple_short_category not in", values, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryBetween(String value1, String value2) {
            addCriterion("simple_short_category between", value1, value2, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryNotBetween(String value1, String value2) {
            addCriterion("simple_short_category not between", value1, value2, "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryIsNull() {
            addCriterion("complex_full_category is null");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryIsNotNull() {
            addCriterion("complex_full_category is not null");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryEqualTo(String value) {
            addCriterion("complex_full_category =", value, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryNotEqualTo(String value) {
            addCriterion("complex_full_category <>", value, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryGreaterThan(String value) {
            addCriterion("complex_full_category >", value, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("complex_full_category >=", value, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryLessThan(String value) {
            addCriterion("complex_full_category <", value, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryLessThanOrEqualTo(String value) {
            addCriterion("complex_full_category <=", value, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryLike(String value) {
            addCriterion("complex_full_category like", value, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryNotLike(String value) {
            addCriterion("complex_full_category not like", value, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryIn(List<String> values) {
            addCriterion("complex_full_category in", values, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryNotIn(List<String> values) {
            addCriterion("complex_full_category not in", values, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryBetween(String value1, String value2) {
            addCriterion("complex_full_category between", value1, value2, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryNotBetween(String value1, String value2) {
            addCriterion("complex_full_category not between", value1, value2, "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryIsNull() {
            addCriterion("complex_short_category is null");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryIsNotNull() {
            addCriterion("complex_short_category is not null");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryEqualTo(String value) {
            addCriterion("complex_short_category =", value, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryNotEqualTo(String value) {
            addCriterion("complex_short_category <>", value, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryGreaterThan(String value) {
            addCriterion("complex_short_category >", value, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("complex_short_category >=", value, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryLessThan(String value) {
            addCriterion("complex_short_category <", value, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryLessThanOrEqualTo(String value) {
            addCriterion("complex_short_category <=", value, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryLike(String value) {
            addCriterion("complex_short_category like", value, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryNotLike(String value) {
            addCriterion("complex_short_category not like", value, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryIn(List<String> values) {
            addCriterion("complex_short_category in", values, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryNotIn(List<String> values) {
            addCriterion("complex_short_category not in", values, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryBetween(String value1, String value2) {
            addCriterion("complex_short_category between", value1, value2, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryNotBetween(String value1, String value2) {
            addCriterion("complex_short_category not between", value1, value2, "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryIsNull() {
            addCriterion("english_full_category is null");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryIsNotNull() {
            addCriterion("english_full_category is not null");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryEqualTo(String value) {
            addCriterion("english_full_category =", value, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryNotEqualTo(String value) {
            addCriterion("english_full_category <>", value, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryGreaterThan(String value) {
            addCriterion("english_full_category >", value, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("english_full_category >=", value, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryLessThan(String value) {
            addCriterion("english_full_category <", value, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryLessThanOrEqualTo(String value) {
            addCriterion("english_full_category <=", value, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryLike(String value) {
            addCriterion("english_full_category like", value, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryNotLike(String value) {
            addCriterion("english_full_category not like", value, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryIn(List<String> values) {
            addCriterion("english_full_category in", values, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryNotIn(List<String> values) {
            addCriterion("english_full_category not in", values, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryBetween(String value1, String value2) {
            addCriterion("english_full_category between", value1, value2, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryNotBetween(String value1, String value2) {
            addCriterion("english_full_category not between", value1, value2, "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryIsNull() {
            addCriterion("english_short_category is null");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryIsNotNull() {
            addCriterion("english_short_category is not null");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryEqualTo(String value) {
            addCriterion("english_short_category =", value, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryNotEqualTo(String value) {
            addCriterion("english_short_category <>", value, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryGreaterThan(String value) {
            addCriterion("english_short_category >", value, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("english_short_category >=", value, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryLessThan(String value) {
            addCriterion("english_short_category <", value, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryLessThanOrEqualTo(String value) {
            addCriterion("english_short_category <=", value, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryLike(String value) {
            addCriterion("english_short_category like", value, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryNotLike(String value) {
            addCriterion("english_short_category not like", value, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryIn(List<String> values) {
            addCriterion("english_short_category in", values, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryNotIn(List<String> values) {
            addCriterion("english_short_category not in", values, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryBetween(String value1, String value2) {
            addCriterion("english_short_category between", value1, value2, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryNotBetween(String value1, String value2) {
            addCriterion("english_short_category not between", value1, value2, "englishShortCategory");
            return (Criteria) this;
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(id) like", value.toUpperCase(), "id");
            return (Criteria) this;
        }

        public Criteria andSimpleFullCategoryLikeInsensitive(String value) {
            addCriterion("upper(simple_full_category) like", value.toUpperCase(), "simpleFullCategory");
            return (Criteria) this;
        }

        public Criteria andSimpleShortCategoryLikeInsensitive(String value) {
            addCriterion("upper(simple_short_category) like", value.toUpperCase(), "simpleShortCategory");
            return (Criteria) this;
        }

        public Criteria andComplexFullCategoryLikeInsensitive(String value) {
            addCriterion("upper(complex_full_category) like", value.toUpperCase(), "complexFullCategory");
            return (Criteria) this;
        }

        public Criteria andComplexShortCategoryLikeInsensitive(String value) {
            addCriterion("upper(complex_short_category) like", value.toUpperCase(), "complexShortCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishFullCategoryLikeInsensitive(String value) {
            addCriterion("upper(english_full_category) like", value.toUpperCase(), "englishFullCategory");
            return (Criteria) this;
        }

        public Criteria andEnglishShortCategoryLikeInsensitive(String value) {
            addCriterion("upper(english_short_category) like", value.toUpperCase(), "englishShortCategory");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_category_mapping
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}