package com.tj.event.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RaceInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public RaceInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andHomeTeamIsNull() {
            addCriterion("home_team is null");
            return (Criteria) this;
        }

        public Criteria andHomeTeamIsNotNull() {
            addCriterion("home_team is not null");
            return (Criteria) this;
        }

        public Criteria andHomeTeamEqualTo(String value) {
            addCriterion("home_team =", value, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamNotEqualTo(String value) {
            addCriterion("home_team <>", value, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamGreaterThan(String value) {
            addCriterion("home_team >", value, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamGreaterThanOrEqualTo(String value) {
            addCriterion("home_team >=", value, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamLessThan(String value) {
            addCriterion("home_team <", value, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamLessThanOrEqualTo(String value) {
            addCriterion("home_team <=", value, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamLike(String value) {
            addCriterion("home_team like", value, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamNotLike(String value) {
            addCriterion("home_team not like", value, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamIn(List<String> values) {
            addCriterion("home_team in", values, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamNotIn(List<String> values) {
            addCriterion("home_team not in", values, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamBetween(String value1, String value2) {
            addCriterion("home_team between", value1, value2, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andHomeTeamNotBetween(String value1, String value2) {
            addCriterion("home_team not between", value1, value2, "homeTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamIsNull() {
            addCriterion("visit_team is null");
            return (Criteria) this;
        }

        public Criteria andVisitTeamIsNotNull() {
            addCriterion("visit_team is not null");
            return (Criteria) this;
        }

        public Criteria andVisitTeamEqualTo(String value) {
            addCriterion("visit_team =", value, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamNotEqualTo(String value) {
            addCriterion("visit_team <>", value, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamGreaterThan(String value) {
            addCriterion("visit_team >", value, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamGreaterThanOrEqualTo(String value) {
            addCriterion("visit_team >=", value, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamLessThan(String value) {
            addCriterion("visit_team <", value, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamLessThanOrEqualTo(String value) {
            addCriterion("visit_team <=", value, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamLike(String value) {
            addCriterion("visit_team like", value, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamNotLike(String value) {
            addCriterion("visit_team not like", value, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamIn(List<String> values) {
            addCriterion("visit_team in", values, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamNotIn(List<String> values) {
            addCriterion("visit_team not in", values, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamBetween(String value1, String value2) {
            addCriterion("visit_team between", value1, value2, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamNotBetween(String value1, String value2) {
            addCriterion("visit_team not between", value1, value2, "visitTeam");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusIsNull() {
            addCriterion("shelves_status is null");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusIsNotNull() {
            addCriterion("shelves_status is not null");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusEqualTo(Integer value) {
            addCriterion("shelves_status =", value, "shelvesStatus");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusNotEqualTo(Integer value) {
            addCriterion("shelves_status <>", value, "shelvesStatus");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusGreaterThan(Integer value) {
            addCriterion("shelves_status >", value, "shelvesStatus");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("shelves_status >=", value, "shelvesStatus");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusLessThan(Integer value) {
            addCriterion("shelves_status <", value, "shelvesStatus");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusLessThanOrEqualTo(Integer value) {
            addCriterion("shelves_status <=", value, "shelvesStatus");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusIn(List<Integer> values) {
            addCriterion("shelves_status in", values, "shelvesStatus");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusNotIn(List<Integer> values) {
            addCriterion("shelves_status not in", values, "shelvesStatus");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusBetween(Integer value1, Integer value2) {
            addCriterion("shelves_status between", value1, value2, "shelvesStatus");
            return (Criteria) this;
        }

        public Criteria andShelvesStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("shelves_status not between", value1, value2, "shelvesStatus");
            return (Criteria) this;
        }

        public Criteria andRaceStatusIsNull() {
            addCriterion("race_status is null");
            return (Criteria) this;
        }

        public Criteria andRaceStatusIsNotNull() {
            addCriterion("race_status is not null");
            return (Criteria) this;
        }

        public Criteria andRaceStatusEqualTo(Integer value) {
            addCriterion("race_status =", value, "raceStatus");
            return (Criteria) this;
        }

        public Criteria andRaceStatusNotEqualTo(Integer value) {
            addCriterion("race_status <>", value, "raceStatus");
            return (Criteria) this;
        }

        public Criteria andRaceStatusGreaterThan(Integer value) {
            addCriterion("race_status >", value, "raceStatus");
            return (Criteria) this;
        }

        public Criteria andRaceStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("race_status >=", value, "raceStatus");
            return (Criteria) this;
        }

        public Criteria andRaceStatusLessThan(Integer value) {
            addCriterion("race_status <", value, "raceStatus");
            return (Criteria) this;
        }

        public Criteria andRaceStatusLessThanOrEqualTo(Integer value) {
            addCriterion("race_status <=", value, "raceStatus");
            return (Criteria) this;
        }

        public Criteria andRaceStatusIn(List<Integer> values) {
            addCriterion("race_status in", values, "raceStatus");
            return (Criteria) this;
        }

        public Criteria andRaceStatusNotIn(List<Integer> values) {
            addCriterion("race_status not in", values, "raceStatus");
            return (Criteria) this;
        }

        public Criteria andRaceStatusBetween(Integer value1, Integer value2) {
            addCriterion("race_status between", value1, value2, "raceStatus");
            return (Criteria) this;
        }

        public Criteria andRaceStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("race_status not between", value1, value2, "raceStatus");
            return (Criteria) this;
        }

        public Criteria andWinTeamIsNull() {
            addCriterion("win_team is null");
            return (Criteria) this;
        }

        public Criteria andWinTeamIsNotNull() {
            addCriterion("win_team is not null");
            return (Criteria) this;
        }

        public Criteria andWinTeamEqualTo(String value) {
            addCriterion("win_team =", value, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamNotEqualTo(String value) {
            addCriterion("win_team <>", value, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamGreaterThan(String value) {
            addCriterion("win_team >", value, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamGreaterThanOrEqualTo(String value) {
            addCriterion("win_team >=", value, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamLessThan(String value) {
            addCriterion("win_team <", value, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamLessThanOrEqualTo(String value) {
            addCriterion("win_team <=", value, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamLike(String value) {
            addCriterion("win_team like", value, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamNotLike(String value) {
            addCriterion("win_team not like", value, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamIn(List<String> values) {
            addCriterion("win_team in", values, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamNotIn(List<String> values) {
            addCriterion("win_team not in", values, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamBetween(String value1, String value2) {
            addCriterion("win_team between", value1, value2, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamNotBetween(String value1, String value2) {
            addCriterion("win_team not between", value1, value2, "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinResultIsNull() {
            addCriterion("win_result is null");
            return (Criteria) this;
        }

        public Criteria andWinResultIsNotNull() {
            addCriterion("win_result is not null");
            return (Criteria) this;
        }

        public Criteria andWinResultEqualTo(String value) {
            addCriterion("win_result =", value, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultNotEqualTo(String value) {
            addCriterion("win_result <>", value, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultGreaterThan(String value) {
            addCriterion("win_result >", value, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultGreaterThanOrEqualTo(String value) {
            addCriterion("win_result >=", value, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultLessThan(String value) {
            addCriterion("win_result <", value, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultLessThanOrEqualTo(String value) {
            addCriterion("win_result <=", value, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultLike(String value) {
            addCriterion("win_result like", value, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultNotLike(String value) {
            addCriterion("win_result not like", value, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultIn(List<String> values) {
            addCriterion("win_result in", values, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultNotIn(List<String> values) {
            addCriterion("win_result not in", values, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultBetween(String value1, String value2) {
            addCriterion("win_result between", value1, value2, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinResultNotBetween(String value1, String value2) {
            addCriterion("win_result not between", value1, value2, "winResult");
            return (Criteria) this;
        }

        public Criteria andWinTypeIsNull() {
            addCriterion("win_type is null");
            return (Criteria) this;
        }

        public Criteria andWinTypeIsNotNull() {
            addCriterion("win_type is not null");
            return (Criteria) this;
        }

        public Criteria andWinTypeEqualTo(Integer value) {
            addCriterion("win_type =", value, "winType");
            return (Criteria) this;
        }

        public Criteria andWinTypeNotEqualTo(Integer value) {
            addCriterion("win_type <>", value, "winType");
            return (Criteria) this;
        }

        public Criteria andWinTypeGreaterThan(Integer value) {
            addCriterion("win_type >", value, "winType");
            return (Criteria) this;
        }

        public Criteria andWinTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("win_type >=", value, "winType");
            return (Criteria) this;
        }

        public Criteria andWinTypeLessThan(Integer value) {
            addCriterion("win_type <", value, "winType");
            return (Criteria) this;
        }

        public Criteria andWinTypeLessThanOrEqualTo(Integer value) {
            addCriterion("win_type <=", value, "winType");
            return (Criteria) this;
        }

        public Criteria andWinTypeIn(List<Integer> values) {
            addCriterion("win_type in", values, "winType");
            return (Criteria) this;
        }

        public Criteria andWinTypeNotIn(List<Integer> values) {
            addCriterion("win_type not in", values, "winType");
            return (Criteria) this;
        }

        public Criteria andWinTypeBetween(Integer value1, Integer value2) {
            addCriterion("win_type between", value1, value2, "winType");
            return (Criteria) this;
        }

        public Criteria andWinTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("win_type not between", value1, value2, "winType");
            return (Criteria) this;
        }

        public Criteria andHalfResultIsNull() {
            addCriterion("half_result is null");
            return (Criteria) this;
        }

        public Criteria andHalfResultIsNotNull() {
            addCriterion("half_result is not null");
            return (Criteria) this;
        }

        public Criteria andHalfResultEqualTo(String value) {
            addCriterion("half_result =", value, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultNotEqualTo(String value) {
            addCriterion("half_result <>", value, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultGreaterThan(String value) {
            addCriterion("half_result >", value, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultGreaterThanOrEqualTo(String value) {
            addCriterion("half_result >=", value, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultLessThan(String value) {
            addCriterion("half_result <", value, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultLessThanOrEqualTo(String value) {
            addCriterion("half_result <=", value, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultLike(String value) {
            addCriterion("half_result like", value, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultNotLike(String value) {
            addCriterion("half_result not like", value, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultIn(List<String> values) {
            addCriterion("half_result in", values, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultNotIn(List<String> values) {
            addCriterion("half_result not in", values, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultBetween(String value1, String value2) {
            addCriterion("half_result between", value1, value2, "halfResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultNotBetween(String value1, String value2) {
            addCriterion("half_result not between", value1, value2, "halfResult");
            return (Criteria) this;
        }

        public Criteria andIsRecommendIsNull() {
            addCriterion("is_recommend is null");
            return (Criteria) this;
        }

        public Criteria andIsRecommendIsNotNull() {
            addCriterion("is_recommend is not null");
            return (Criteria) this;
        }

        public Criteria andIsRecommendEqualTo(Integer value) {
            addCriterion("is_recommend =", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendNotEqualTo(Integer value) {
            addCriterion("is_recommend <>", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendGreaterThan(Integer value) {
            addCriterion("is_recommend >", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_recommend >=", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendLessThan(Integer value) {
            addCriterion("is_recommend <", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendLessThanOrEqualTo(Integer value) {
            addCriterion("is_recommend <=", value, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendIn(List<Integer> values) {
            addCriterion("is_recommend in", values, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendNotIn(List<Integer> values) {
            addCriterion("is_recommend not in", values, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendBetween(Integer value1, Integer value2) {
            addCriterion("is_recommend between", value1, value2, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andIsRecommendNotBetween(Integer value1, Integer value2) {
            addCriterion("is_recommend not between", value1, value2, "isRecommend");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(BigDecimal value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(BigDecimal value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(BigDecimal value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(BigDecimal value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<BigDecimal> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<BigDecimal> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andOpenStatusIsNull() {
            addCriterion("open_status is null");
            return (Criteria) this;
        }

        public Criteria andOpenStatusIsNotNull() {
            addCriterion("open_status is not null");
            return (Criteria) this;
        }

        public Criteria andOpenStatusEqualTo(Integer value) {
            addCriterion("open_status =", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusNotEqualTo(Integer value) {
            addCriterion("open_status <>", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusGreaterThan(Integer value) {
            addCriterion("open_status >", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("open_status >=", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusLessThan(Integer value) {
            addCriterion("open_status <", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusLessThanOrEqualTo(Integer value) {
            addCriterion("open_status <=", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusIn(List<Integer> values) {
            addCriterion("open_status in", values, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusNotIn(List<Integer> values) {
            addCriterion("open_status not in", values, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusBetween(Integer value1, Integer value2) {
            addCriterion("open_status between", value1, value2, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("open_status not between", value1, value2, "openStatus");
            return (Criteria) this;
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(id) like", value.toUpperCase(), "id");
            return (Criteria) this;
        }

        public Criteria andCategoryLikeInsensitive(String value) {
            addCriterion("upper(category) like", value.toUpperCase(), "category");
            return (Criteria) this;
        }

        public Criteria andHomeTeamLikeInsensitive(String value) {
            addCriterion("upper(home_team) like", value.toUpperCase(), "homeTeam");
            return (Criteria) this;
        }

        public Criteria andVisitTeamLikeInsensitive(String value) {
            addCriterion("upper(visit_team) like", value.toUpperCase(), "visitTeam");
            return (Criteria) this;
        }

        public Criteria andWinTeamLikeInsensitive(String value) {
            addCriterion("upper(win_team) like", value.toUpperCase(), "winTeam");
            return (Criteria) this;
        }

        public Criteria andWinResultLikeInsensitive(String value) {
            addCriterion("upper(win_result) like", value.toUpperCase(), "winResult");
            return (Criteria) this;
        }

        public Criteria andHalfResultLikeInsensitive(String value) {
            addCriterion("upper(half_result) like", value.toUpperCase(), "halfResult");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_race_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}