package com.tj.event.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RaceRebateInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_rebate_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_rebate_info.race_id
     *
     * @mbg.generated
     */
    private String raceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_rebate_info.rule
     *
     * @mbg.generated
     */
    private String rule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_rebate_info.rule_type
     *
     * @mbg.generated
     */
    private Integer ruleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_rebate_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_rebate_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_rebate_info.valid_amount
     *
     * @mbg.generated
     */
    private BigDecimal validAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_rebate_info.open_status
     *
     * @mbg.generated
     */
    private Integer openStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_race_rebate_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_rebate_info.id
     *
     * @return the value of t_race_rebate_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_rebate_info.id
     *
     * @param id the value for t_race_rebate_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_rebate_info.race_id
     *
     * @return the value of t_race_rebate_info.race_id
     *
     * @mbg.generated
     */
    public String getRaceId() {
        return raceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_rebate_info.race_id
     *
     * @param raceId the value for t_race_rebate_info.race_id
     *
     * @mbg.generated
     */
    public void setRaceId(String raceId) {
        this.raceId = raceId == null ? null : raceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_rebate_info.rule
     *
     * @return the value of t_race_rebate_info.rule
     *
     * @mbg.generated
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_rebate_info.rule
     *
     * @param rule the value for t_race_rebate_info.rule
     *
     * @mbg.generated
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_rebate_info.rule_type
     *
     * @return the value of t_race_rebate_info.rule_type
     *
     * @mbg.generated
     */
    public Integer getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_rebate_info.rule_type
     *
     * @param ruleType the value for t_race_rebate_info.rule_type
     *
     * @mbg.generated
     */
    public void setRuleType(Integer ruleType) {
        this.ruleType = ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_rebate_info.create_time
     *
     * @return the value of t_race_rebate_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_rebate_info.create_time
     *
     * @param createTime the value for t_race_rebate_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_rebate_info.update_time
     *
     * @return the value of t_race_rebate_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_rebate_info.update_time
     *
     * @param updateTime the value for t_race_rebate_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_rebate_info.valid_amount
     *
     * @return the value of t_race_rebate_info.valid_amount
     *
     * @mbg.generated
     */
    public BigDecimal getValidAmount() {
        return validAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_rebate_info.valid_amount
     *
     * @param validAmount the value for t_race_rebate_info.valid_amount
     *
     * @mbg.generated
     */
    public void setValidAmount(BigDecimal validAmount) {
        this.validAmount = validAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_rebate_info.open_status
     *
     * @return the value of t_race_rebate_info.open_status
     *
     * @mbg.generated
     */
    public Integer getOpenStatus() {
        return openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_rebate_info.open_status
     *
     * @param openStatus the value for t_race_rebate_info.open_status
     *
     * @mbg.generated
     */
    public void setOpenStatus(Integer openStatus) {
        this.openStatus = openStatus;
    }
}