package com.tj.event.domain;

import java.util.ArrayList;
import java.util.List;

public class TeamMappingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public TeamMappingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamIsNull() {
            addCriterion("simple_team is null");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamIsNotNull() {
            addCriterion("simple_team is not null");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamEqualTo(String value) {
            addCriterion("simple_team =", value, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamNotEqualTo(String value) {
            addCriterion("simple_team <>", value, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamGreaterThan(String value) {
            addCriterion("simple_team >", value, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamGreaterThanOrEqualTo(String value) {
            addCriterion("simple_team >=", value, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamLessThan(String value) {
            addCriterion("simple_team <", value, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamLessThanOrEqualTo(String value) {
            addCriterion("simple_team <=", value, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamLike(String value) {
            addCriterion("simple_team like", value, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamNotLike(String value) {
            addCriterion("simple_team not like", value, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamIn(List<String> values) {
            addCriterion("simple_team in", values, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamNotIn(List<String> values) {
            addCriterion("simple_team not in", values, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamBetween(String value1, String value2) {
            addCriterion("simple_team between", value1, value2, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamNotBetween(String value1, String value2) {
            addCriterion("simple_team not between", value1, value2, "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamIsNull() {
            addCriterion("complex_team is null");
            return (Criteria) this;
        }

        public Criteria andComplexTeamIsNotNull() {
            addCriterion("complex_team is not null");
            return (Criteria) this;
        }

        public Criteria andComplexTeamEqualTo(String value) {
            addCriterion("complex_team =", value, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamNotEqualTo(String value) {
            addCriterion("complex_team <>", value, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamGreaterThan(String value) {
            addCriterion("complex_team >", value, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamGreaterThanOrEqualTo(String value) {
            addCriterion("complex_team >=", value, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamLessThan(String value) {
            addCriterion("complex_team <", value, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamLessThanOrEqualTo(String value) {
            addCriterion("complex_team <=", value, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamLike(String value) {
            addCriterion("complex_team like", value, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamNotLike(String value) {
            addCriterion("complex_team not like", value, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamIn(List<String> values) {
            addCriterion("complex_team in", values, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamNotIn(List<String> values) {
            addCriterion("complex_team not in", values, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamBetween(String value1, String value2) {
            addCriterion("complex_team between", value1, value2, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamNotBetween(String value1, String value2) {
            addCriterion("complex_team not between", value1, value2, "complexTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamIsNull() {
            addCriterion("english_team is null");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamIsNotNull() {
            addCriterion("english_team is not null");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamEqualTo(String value) {
            addCriterion("english_team =", value, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamNotEqualTo(String value) {
            addCriterion("english_team <>", value, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamGreaterThan(String value) {
            addCriterion("english_team >", value, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamGreaterThanOrEqualTo(String value) {
            addCriterion("english_team >=", value, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamLessThan(String value) {
            addCriterion("english_team <", value, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamLessThanOrEqualTo(String value) {
            addCriterion("english_team <=", value, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamLike(String value) {
            addCriterion("english_team like", value, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamNotLike(String value) {
            addCriterion("english_team not like", value, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamIn(List<String> values) {
            addCriterion("english_team in", values, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamNotIn(List<String> values) {
            addCriterion("english_team not in", values, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamBetween(String value1, String value2) {
            addCriterion("english_team between", value1, value2, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamNotBetween(String value1, String value2) {
            addCriterion("english_team not between", value1, value2, "englishTeam");
            return (Criteria) this;
        }

        public Criteria andImgPathIsNull() {
            addCriterion("img_path is null");
            return (Criteria) this;
        }

        public Criteria andImgPathIsNotNull() {
            addCriterion("img_path is not null");
            return (Criteria) this;
        }

        public Criteria andImgPathEqualTo(String value) {
            addCriterion("img_path =", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotEqualTo(String value) {
            addCriterion("img_path <>", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathGreaterThan(String value) {
            addCriterion("img_path >", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathGreaterThanOrEqualTo(String value) {
            addCriterion("img_path >=", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLessThan(String value) {
            addCriterion("img_path <", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLessThanOrEqualTo(String value) {
            addCriterion("img_path <=", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLike(String value) {
            addCriterion("img_path like", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotLike(String value) {
            addCriterion("img_path not like", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathIn(List<String> values) {
            addCriterion("img_path in", values, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotIn(List<String> values) {
            addCriterion("img_path not in", values, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathBetween(String value1, String value2) {
            addCriterion("img_path between", value1, value2, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotBetween(String value1, String value2) {
            addCriterion("img_path not between", value1, value2, "imgPath");
            return (Criteria) this;
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(id) like", value.toUpperCase(), "id");
            return (Criteria) this;
        }

        public Criteria andSimpleTeamLikeInsensitive(String value) {
            addCriterion("upper(simple_team) like", value.toUpperCase(), "simpleTeam");
            return (Criteria) this;
        }

        public Criteria andComplexTeamLikeInsensitive(String value) {
            addCriterion("upper(complex_team) like", value.toUpperCase(), "complexTeam");
            return (Criteria) this;
        }

        public Criteria andEnglishTeamLikeInsensitive(String value) {
            addCriterion("upper(english_team) like", value.toUpperCase(), "englishTeam");
            return (Criteria) this;
        }

        public Criteria andImgPathLikeInsensitive(String value) {
            addCriterion("upper(img_path) like", value.toUpperCase(), "imgPath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_team_mapping
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}