package com.tj.user.domain;

import java.io.Serializable;
import java.util.Date;

public class RegisterInviteRecd implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_regist_invite_recd
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regist_invite_recd.id
     *
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regist_invite_recd.invite_user_id
     *
     * @mbg.generated
     */
    private Integer inviteUserId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regist_invite_recd.invite_code
     *
     * @mbg.generated
     */
    private String inviteCode;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regist_invite_recd.invited_user_id
     *
     * @mbg.generated
     */
    private Integer invitedUserId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regist_invite_recd.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regist_invite_recd.create_time
     *
     * @mbg.generated
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regist_invite_recd.invited_ancestor_ids
     *
     * @mbg.generated
     */
    private String invitedAncestorIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regist_invite_recd.id
     *
     * @return the value of t_regist_invite_recd.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regist_invite_recd.id
     *
     * @param id the value for t_regist_invite_recd.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regist_invite_recd.invite_user_id
     *
     * @return the value of t_regist_invite_recd.invite_user_id
     * @mbg.generated
     */
    public Integer getInviteUserId() {
        return inviteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regist_invite_recd.invite_user_id
     *
     * @param inviteUserId the value for t_regist_invite_recd.invite_user_id
     * @mbg.generated
     */
    public void setInviteUserId(Integer inviteUserId) {
        this.inviteUserId = inviteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regist_invite_recd.invite_code
     *
     * @return the value of t_regist_invite_recd.invite_code
     * @mbg.generated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regist_invite_recd.invite_code
     *
     * @param inviteCode the value for t_regist_invite_recd.invite_code
     * @mbg.generated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regist_invite_recd.invited_user_id
     *
     * @return the value of t_regist_invite_recd.invited_user_id
     * @mbg.generated
     */
    public Integer getInvitedUserId() {
        return invitedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regist_invite_recd.invited_user_id
     *
     * @param invitedUserId the value for t_regist_invite_recd.invited_user_id
     * @mbg.generated
     */
    public void setInvitedUserId(Integer invitedUserId) {
        this.invitedUserId = invitedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regist_invite_recd.update_time
     *
     * @return the value of t_regist_invite_recd.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regist_invite_recd.update_time
     *
     * @param updateTime the value for t_regist_invite_recd.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regist_invite_recd.create_time
     *
     * @return the value of t_regist_invite_recd.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regist_invite_recd.create_time
     *
     * @param createTime the value for t_regist_invite_recd.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regist_invite_recd.invited_ancestor_ids
     *
     * @return the value of t_regist_invite_recd.invited_ancestor_ids
     * @mbg.generated
     */
    public String getInvitedAncestorIds() {
        return invitedAncestorIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regist_invite_recd.invited_ancestor_ids
     *
     * @param invitedAncestorIds the value for t_regist_invite_recd.invited_ancestor_ids
     * @mbg.generated
     */
    public void setInvitedAncestorIds(String invitedAncestorIds) {
        this.invitedAncestorIds = invitedAncestorIds == null ? null : invitedAncestorIds.trim();
    }
}