package com.tj.bet.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DiveRuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public DiveRuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIncreaseIsNull() {
            addCriterion("increase is null");
            return (Criteria) this;
        }

        public Criteria andIncreaseIsNotNull() {
            addCriterion("increase is not null");
            return (Criteria) this;
        }

        public Criteria andIncreaseEqualTo(BigDecimal value) {
            addCriterion("increase =", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseNotEqualTo(BigDecimal value) {
            addCriterion("increase <>", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseGreaterThan(BigDecimal value) {
            addCriterion("increase >", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("increase >=", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseLessThan(BigDecimal value) {
            addCriterion("increase <", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseLessThanOrEqualTo(BigDecimal value) {
            addCriterion("increase <=", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseIn(List<BigDecimal> values) {
            addCriterion("increase in", values, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseNotIn(List<BigDecimal> values) {
            addCriterion("increase not in", values, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("increase between", value1, value2, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("increase not between", value1, value2, "increase");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeIsNull() {
            addCriterion("autochange_time is null");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeIsNotNull() {
            addCriterion("autochange_time is not null");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeEqualTo(BigDecimal value) {
            addCriterion("autochange_time =", value, "autochangeTime");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeNotEqualTo(BigDecimal value) {
            addCriterion("autochange_time <>", value, "autochangeTime");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeGreaterThan(BigDecimal value) {
            addCriterion("autochange_time >", value, "autochangeTime");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("autochange_time >=", value, "autochangeTime");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeLessThan(BigDecimal value) {
            addCriterion("autochange_time <", value, "autochangeTime");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("autochange_time <=", value, "autochangeTime");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeIn(List<BigDecimal> values) {
            addCriterion("autochange_time in", values, "autochangeTime");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeNotIn(List<BigDecimal> values) {
            addCriterion("autochange_time not in", values, "autochangeTime");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("autochange_time between", value1, value2, "autochangeTime");
            return (Criteria) this;
        }

        public Criteria andAutochangeTimeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("autochange_time not between", value1, value2, "autochangeTime");
            return (Criteria) this;
        }

        public Criteria andStartAmountIsNull() {
            addCriterion("start_amount is null");
            return (Criteria) this;
        }

        public Criteria andStartAmountIsNotNull() {
            addCriterion("start_amount is not null");
            return (Criteria) this;
        }

        public Criteria andStartAmountEqualTo(BigDecimal value) {
            addCriterion("start_amount =", value, "startAmount");
            return (Criteria) this;
        }

        public Criteria andStartAmountNotEqualTo(BigDecimal value) {
            addCriterion("start_amount <>", value, "startAmount");
            return (Criteria) this;
        }

        public Criteria andStartAmountGreaterThan(BigDecimal value) {
            addCriterion("start_amount >", value, "startAmount");
            return (Criteria) this;
        }

        public Criteria andStartAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("start_amount >=", value, "startAmount");
            return (Criteria) this;
        }

        public Criteria andStartAmountLessThan(BigDecimal value) {
            addCriterion("start_amount <", value, "startAmount");
            return (Criteria) this;
        }

        public Criteria andStartAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("start_amount <=", value, "startAmount");
            return (Criteria) this;
        }

        public Criteria andStartAmountIn(List<BigDecimal> values) {
            addCriterion("start_amount in", values, "startAmount");
            return (Criteria) this;
        }

        public Criteria andStartAmountNotIn(List<BigDecimal> values) {
            addCriterion("start_amount not in", values, "startAmount");
            return (Criteria) this;
        }

        public Criteria andStartAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("start_amount between", value1, value2, "startAmount");
            return (Criteria) this;
        }

        public Criteria andStartAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("start_amount not between", value1, value2, "startAmount");
            return (Criteria) this;
        }

        public Criteria andStartRebateIsNull() {
            addCriterion("start_rebate is null");
            return (Criteria) this;
        }

        public Criteria andStartRebateIsNotNull() {
            addCriterion("start_rebate is not null");
            return (Criteria) this;
        }

        public Criteria andStartRebateEqualTo(BigDecimal value) {
            addCriterion("start_rebate =", value, "startRebate");
            return (Criteria) this;
        }

        public Criteria andStartRebateNotEqualTo(BigDecimal value) {
            addCriterion("start_rebate <>", value, "startRebate");
            return (Criteria) this;
        }

        public Criteria andStartRebateGreaterThan(BigDecimal value) {
            addCriterion("start_rebate >", value, "startRebate");
            return (Criteria) this;
        }

        public Criteria andStartRebateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("start_rebate >=", value, "startRebate");
            return (Criteria) this;
        }

        public Criteria andStartRebateLessThan(BigDecimal value) {
            addCriterion("start_rebate <", value, "startRebate");
            return (Criteria) this;
        }

        public Criteria andStartRebateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("start_rebate <=", value, "startRebate");
            return (Criteria) this;
        }

        public Criteria andStartRebateIn(List<BigDecimal> values) {
            addCriterion("start_rebate in", values, "startRebate");
            return (Criteria) this;
        }

        public Criteria andStartRebateNotIn(List<BigDecimal> values) {
            addCriterion("start_rebate not in", values, "startRebate");
            return (Criteria) this;
        }

        public Criteria andStartRebateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("start_rebate between", value1, value2, "startRebate");
            return (Criteria) this;
        }

        public Criteria andStartRebateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("start_rebate not between", value1, value2, "startRebate");
            return (Criteria) this;
        }

        public Criteria andEndRebateIsNull() {
            addCriterion("end_rebate is null");
            return (Criteria) this;
        }

        public Criteria andEndRebateIsNotNull() {
            addCriterion("end_rebate is not null");
            return (Criteria) this;
        }

        public Criteria andEndRebateEqualTo(BigDecimal value) {
            addCriterion("end_rebate =", value, "endRebate");
            return (Criteria) this;
        }

        public Criteria andEndRebateNotEqualTo(BigDecimal value) {
            addCriterion("end_rebate <>", value, "endRebate");
            return (Criteria) this;
        }

        public Criteria andEndRebateGreaterThan(BigDecimal value) {
            addCriterion("end_rebate >", value, "endRebate");
            return (Criteria) this;
        }

        public Criteria andEndRebateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("end_rebate >=", value, "endRebate");
            return (Criteria) this;
        }

        public Criteria andEndRebateLessThan(BigDecimal value) {
            addCriterion("end_rebate <", value, "endRebate");
            return (Criteria) this;
        }

        public Criteria andEndRebateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("end_rebate <=", value, "endRebate");
            return (Criteria) this;
        }

        public Criteria andEndRebateIn(List<BigDecimal> values) {
            addCriterion("end_rebate in", values, "endRebate");
            return (Criteria) this;
        }

        public Criteria andEndRebateNotIn(List<BigDecimal> values) {
            addCriterion("end_rebate not in", values, "endRebate");
            return (Criteria) this;
        }

        public Criteria andEndRebateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("end_rebate between", value1, value2, "endRebate");
            return (Criteria) this;
        }

        public Criteria andEndRebateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("end_rebate not between", value1, value2, "endRebate");
            return (Criteria) this;
        }

        public Criteria andRuleTypeIsNull() {
            addCriterion("rule_type is null");
            return (Criteria) this;
        }

        public Criteria andRuleTypeIsNotNull() {
            addCriterion("rule_type is not null");
            return (Criteria) this;
        }

        public Criteria andRuleTypeEqualTo(Integer value) {
            addCriterion("rule_type =", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotEqualTo(Integer value) {
            addCriterion("rule_type <>", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeGreaterThan(Integer value) {
            addCriterion("rule_type >", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("rule_type >=", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeLessThan(Integer value) {
            addCriterion("rule_type <", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeLessThanOrEqualTo(Integer value) {
            addCriterion("rule_type <=", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeIn(List<Integer> values) {
            addCriterion("rule_type in", values, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotIn(List<Integer> values) {
            addCriterion("rule_type not in", values, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeBetween(Integer value1, Integer value2) {
            addCriterion("rule_type between", value1, value2, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("rule_type not between", value1, value2, "ruleType");
            return (Criteria) this;
        }

        public Criteria andEnableStatusIsNull() {
            addCriterion("enable_status is null");
            return (Criteria) this;
        }

        public Criteria andEnableStatusIsNotNull() {
            addCriterion("enable_status is not null");
            return (Criteria) this;
        }

        public Criteria andEnableStatusEqualTo(Integer value) {
            addCriterion("enable_status =", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusNotEqualTo(Integer value) {
            addCriterion("enable_status <>", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusGreaterThan(Integer value) {
            addCriterion("enable_status >", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("enable_status >=", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusLessThan(Integer value) {
            addCriterion("enable_status <", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusLessThanOrEqualTo(Integer value) {
            addCriterion("enable_status <=", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusIn(List<Integer> values) {
            addCriterion("enable_status in", values, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusNotIn(List<Integer> values) {
            addCriterion("enable_status not in", values, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusBetween(Integer value1, Integer value2) {
            addCriterion("enable_status between", value1, value2, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("enable_status not between", value1, value2, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSysStatusIsNull() {
            addCriterion("sys_status is null");
            return (Criteria) this;
        }

        public Criteria andSysStatusIsNotNull() {
            addCriterion("sys_status is not null");
            return (Criteria) this;
        }

        public Criteria andSysStatusEqualTo(Integer value) {
            addCriterion("sys_status =", value, "sysStatus");
            return (Criteria) this;
        }

        public Criteria andSysStatusNotEqualTo(Integer value) {
            addCriterion("sys_status <>", value, "sysStatus");
            return (Criteria) this;
        }

        public Criteria andSysStatusGreaterThan(Integer value) {
            addCriterion("sys_status >", value, "sysStatus");
            return (Criteria) this;
        }

        public Criteria andSysStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sys_status >=", value, "sysStatus");
            return (Criteria) this;
        }

        public Criteria andSysStatusLessThan(Integer value) {
            addCriterion("sys_status <", value, "sysStatus");
            return (Criteria) this;
        }

        public Criteria andSysStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sys_status <=", value, "sysStatus");
            return (Criteria) this;
        }

        public Criteria andSysStatusIn(List<Integer> values) {
            addCriterion("sys_status in", values, "sysStatus");
            return (Criteria) this;
        }

        public Criteria andSysStatusNotIn(List<Integer> values) {
            addCriterion("sys_status not in", values, "sysStatus");
            return (Criteria) this;
        }

        public Criteria andSysStatusBetween(Integer value1, Integer value2) {
            addCriterion("sys_status between", value1, value2, "sysStatus");
            return (Criteria) this;
        }

        public Criteria andSysStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sys_status not between", value1, value2, "sysStatus");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateIsNull() {
            addCriterion("shut_down_rebate is null");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateIsNotNull() {
            addCriterion("shut_down_rebate is not null");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateEqualTo(BigDecimal value) {
            addCriterion("shut_down_rebate =", value, "shutDownRebate");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateNotEqualTo(BigDecimal value) {
            addCriterion("shut_down_rebate <>", value, "shutDownRebate");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateGreaterThan(BigDecimal value) {
            addCriterion("shut_down_rebate >", value, "shutDownRebate");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shut_down_rebate >=", value, "shutDownRebate");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateLessThan(BigDecimal value) {
            addCriterion("shut_down_rebate <", value, "shutDownRebate");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shut_down_rebate <=", value, "shutDownRebate");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateIn(List<BigDecimal> values) {
            addCriterion("shut_down_rebate in", values, "shutDownRebate");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateNotIn(List<BigDecimal> values) {
            addCriterion("shut_down_rebate not in", values, "shutDownRebate");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shut_down_rebate between", value1, value2, "shutDownRebate");
            return (Criteria) this;
        }

        public Criteria andShutDownRebateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shut_down_rebate not between", value1, value2, "shutDownRebate");
            return (Criteria) this;
        }

        public Criteria andTimeRangeIsNull() {
            addCriterion("time_range is null");
            return (Criteria) this;
        }

        public Criteria andTimeRangeIsNotNull() {
            addCriterion("time_range is not null");
            return (Criteria) this;
        }

        public Criteria andTimeRangeEqualTo(Integer value) {
            addCriterion("time_range =", value, "timeRange");
            return (Criteria) this;
        }

        public Criteria andTimeRangeNotEqualTo(Integer value) {
            addCriterion("time_range <>", value, "timeRange");
            return (Criteria) this;
        }

        public Criteria andTimeRangeGreaterThan(Integer value) {
            addCriterion("time_range >", value, "timeRange");
            return (Criteria) this;
        }

        public Criteria andTimeRangeGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_range >=", value, "timeRange");
            return (Criteria) this;
        }

        public Criteria andTimeRangeLessThan(Integer value) {
            addCriterion("time_range <", value, "timeRange");
            return (Criteria) this;
        }

        public Criteria andTimeRangeLessThanOrEqualTo(Integer value) {
            addCriterion("time_range <=", value, "timeRange");
            return (Criteria) this;
        }

        public Criteria andTimeRangeIn(List<Integer> values) {
            addCriterion("time_range in", values, "timeRange");
            return (Criteria) this;
        }

        public Criteria andTimeRangeNotIn(List<Integer> values) {
            addCriterion("time_range not in", values, "timeRange");
            return (Criteria) this;
        }

        public Criteria andTimeRangeBetween(Integer value1, Integer value2) {
            addCriterion("time_range between", value1, value2, "timeRange");
            return (Criteria) this;
        }

        public Criteria andTimeRangeNotBetween(Integer value1, Integer value2) {
            addCriterion("time_range not between", value1, value2, "timeRange");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_dive_rule
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_dive_rule
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}