package com.tj.bet.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RaceInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_race_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.id
     *
     * @mbg.generated
     */
    private String id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.category
     *
     * @mbg.generated
     */
    private String category;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.start_time
     *
     * @mbg.generated
     */
    private Date startTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.end_time
     *
     * @mbg.generated
     */
    private Date endTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.home_team
     *
     * @mbg.generated
     */
    private String homeTeam;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.visit_team
     *
     * @mbg.generated
     */
    private String visitTeam;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.shelves_status
     *
     * @mbg.generated
     */
    private Integer shelvesStatus;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.race_status
     *
     * @mbg.generated
     */
    private Integer raceStatus;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.win_team
     *
     * @mbg.generated
     */
    private String winTeam;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.win_result
     *
     * @mbg.generated
     */
    private String winResult;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.win_type
     *
     * @mbg.generated
     */
    private Integer winType;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.half_result
     *
     * @mbg.generated
     */
    private String halfResult;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.is_recommend
     *
     * @mbg.generated
     */
    private Integer isRecommend;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.weight
     *
     * @mbg.generated
     */
    private BigDecimal weight;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_info.open_status
     *
     * @mbg.generated
     */
    private Integer openStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.id
     *
     * @return the value of t_race_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.id
     *
     * @param id the value for t_race_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.category
     *
     * @return the value of t_race_info.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.category
     *
     * @param category the value for t_race_info.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.start_time
     *
     * @return the value of t_race_info.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.start_time
     *
     * @param startTime the value for t_race_info.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.end_time
     *
     * @return the value of t_race_info.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.end_time
     *
     * @param endTime the value for t_race_info.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.home_team
     *
     * @return the value of t_race_info.home_team
     *
     * @mbg.generated
     */
    public String getHomeTeam() {
        return homeTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.home_team
     *
     * @param homeTeam the value for t_race_info.home_team
     *
     * @mbg.generated
     */
    public void setHomeTeam(String homeTeam) {
        this.homeTeam = homeTeam == null ? null : homeTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.visit_team
     *
     * @return the value of t_race_info.visit_team
     *
     * @mbg.generated
     */
    public String getVisitTeam() {
        return visitTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.visit_team
     *
     * @param visitTeam the value for t_race_info.visit_team
     *
     * @mbg.generated
     */
    public void setVisitTeam(String visitTeam) {
        this.visitTeam = visitTeam == null ? null : visitTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.create_time
     *
     * @return the value of t_race_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.create_time
     *
     * @param createTime the value for t_race_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.update_time
     *
     * @return the value of t_race_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.update_time
     *
     * @param updateTime the value for t_race_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.shelves_status
     *
     * @return the value of t_race_info.shelves_status
     *
     * @mbg.generated
     */
    public Integer getShelvesStatus() {
        return shelvesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.shelves_status
     *
     * @param shelvesStatus the value for t_race_info.shelves_status
     *
     * @mbg.generated
     */
    public void setShelvesStatus(Integer shelvesStatus) {
        this.shelvesStatus = shelvesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.race_status
     *
     * @return the value of t_race_info.race_status
     *
     * @mbg.generated
     */
    public Integer getRaceStatus() {
        return raceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.race_status
     *
     * @param raceStatus the value for t_race_info.race_status
     *
     * @mbg.generated
     */
    public void setRaceStatus(Integer raceStatus) {
        this.raceStatus = raceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.win_team
     *
     * @return the value of t_race_info.win_team
     *
     * @mbg.generated
     */
    public String getWinTeam() {
        return winTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.win_team
     *
     * @param winTeam the value for t_race_info.win_team
     *
     * @mbg.generated
     */
    public void setWinTeam(String winTeam) {
        this.winTeam = winTeam == null ? null : winTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.win_result
     *
     * @return the value of t_race_info.win_result
     *
     * @mbg.generated
     */
    public String getWinResult() {
        return winResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.win_result
     *
     * @param winResult the value for t_race_info.win_result
     *
     * @mbg.generated
     */
    public void setWinResult(String winResult) {
        this.winResult = winResult == null ? null : winResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.win_type
     *
     * @return the value of t_race_info.win_type
     *
     * @mbg.generated
     */
    public Integer getWinType() {
        return winType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.win_type
     *
     * @param winType the value for t_race_info.win_type
     *
     * @mbg.generated
     */
    public void setWinType(Integer winType) {
        this.winType = winType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.half_result
     *
     * @return the value of t_race_info.half_result
     *
     * @mbg.generated
     */
    public String getHalfResult() {
        return halfResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.half_result
     *
     * @param halfResult the value for t_race_info.half_result
     *
     * @mbg.generated
     */
    public void setHalfResult(String halfResult) {
        this.halfResult = halfResult == null ? null : halfResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.is_recommend
     *
     * @return the value of t_race_info.is_recommend
     *
     * @mbg.generated
     */
    public Integer getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.is_recommend
     *
     * @param isRecommend the value for t_race_info.is_recommend
     *
     * @mbg.generated
     */
    public void setIsRecommend(Integer isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.weight
     *
     * @return the value of t_race_info.weight
     *
     * @mbg.generated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.weight
     *
     * @param weight the value for t_race_info.weight
     *
     * @mbg.generated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_info.open_status
     *
     * @return the value of t_race_info.open_status
     *
     * @mbg.generated
     */
    public Integer getOpenStatus() {
        return openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_info.open_status
     *
     * @param openStatus the value for t_race_info.open_status
     * @mbg.generated
     */
    public void setOpenStatus(Integer openStatus) {
        this.openStatus = openStatus;
    }
}