package com.tj.bet.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RaceOddsInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_race_odds_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_odds_info.id
     *
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_odds_info.race_id
     *
     * @mbg.generated
     */
    private String raceId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_odds_info.teams
     *
     * @mbg.generated
     */
    private String teams;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_odds_info.score
     *
     * @mbg.generated
     */
    private String score;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_odds_info.odds
     *
     * @mbg.generated
     */
    private BigDecimal odds;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_odds_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_race_odds_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_odds_info.id
     *
     * @return the value of t_race_odds_info.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_odds_info.id
     *
     * @param id the value for t_race_odds_info.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_odds_info.race_id
     *
     * @return the value of t_race_odds_info.race_id
     * @mbg.generated
     */
    public String getRaceId() {
        return raceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_odds_info.race_id
     *
     * @param raceId the value for t_race_odds_info.race_id
     * @mbg.generated
     */
    public void setRaceId(String raceId) {
        this.raceId = raceId == null ? null : raceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_odds_info.teams
     *
     * @return the value of t_race_odds_info.teams
     * @mbg.generated
     */
    public String getTeams() {
        return teams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_odds_info.teams
     *
     * @param teams the value for t_race_odds_info.teams
     * @mbg.generated
     */
    public void setTeams(String teams) {
        this.teams = teams == null ? null : teams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_odds_info.score
     *
     * @return the value of t_race_odds_info.score
     * @mbg.generated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_odds_info.score
     *
     * @param score the value for t_race_odds_info.score
     * @mbg.generated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_odds_info.odds
     *
     * @return the value of t_race_odds_info.odds
     * @mbg.generated
     */
    public BigDecimal getOdds() {
        return odds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_odds_info.odds
     *
     * @param odds the value for t_race_odds_info.odds
     * @mbg.generated
     */
    public void setOdds(BigDecimal odds) {
        this.odds = odds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_odds_info.create_time
     *
     * @return the value of t_race_odds_info.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_odds_info.create_time
     *
     * @param createTime the value for t_race_odds_info.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_race_odds_info.update_time
     *
     * @return the value of t_race_odds_info.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_race_odds_info.update_time
     *
     * @param updateTime the value for t_race_odds_info.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}