package com.tj.bet.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RebateRecd implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_rebate_recd
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rebate_recd.id
     *
     * @mbg.generated
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rebate_recd.user_id
     *
     * @mbg.generated
     */
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rebate_recd.related_bet_id
     *
     * @mbg.generated
     */
    private Long relatedBetId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rebate_recd.rebate_amount
     *
     * @mbg.generated
     */
    private BigDecimal rebateAmount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rebate_recd.rebate_status
     *
     * @mbg.generated
     */
    private Integer rebateStatus;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rebate_recd.create_time
     *
     * @mbg.generated
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rebate_recd.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rebate_recd.id
     *
     * @return the value of t_rebate_recd.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rebate_recd.id
     *
     * @param id the value for t_rebate_recd.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rebate_recd.user_id
     *
     * @return the value of t_rebate_recd.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rebate_recd.user_id
     *
     * @param userId the value for t_rebate_recd.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rebate_recd.related_bet_id
     *
     * @return the value of t_rebate_recd.related_bet_id
     * @mbg.generated
     */
    public Long getRelatedBetId() {
        return relatedBetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rebate_recd.related_bet_id
     *
     * @param relatedBetId the value for t_rebate_recd.related_bet_id
     * @mbg.generated
     */
    public void setRelatedBetId(Long relatedBetId) {
        this.relatedBetId = relatedBetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rebate_recd.rebate_amount
     *
     * @return the value of t_rebate_recd.rebate_amount
     * @mbg.generated
     */
    public BigDecimal getRebateAmount() {
        return rebateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rebate_recd.rebate_amount
     *
     * @param rebateAmount the value for t_rebate_recd.rebate_amount
     * @mbg.generated
     */
    public void setRebateAmount(BigDecimal rebateAmount) {
        this.rebateAmount = rebateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rebate_recd.rebate_status
     *
     * @return the value of t_rebate_recd.rebate_status
     * @mbg.generated
     */
    public Integer getRebateStatus() {
        return rebateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rebate_recd.rebate_status
     *
     * @param rebateStatus the value for t_rebate_recd.rebate_status
     * @mbg.generated
     */
    public void setRebateStatus(Integer rebateStatus) {
        this.rebateStatus = rebateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rebate_recd.create_time
     *
     * @return the value of t_rebate_recd.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rebate_recd.create_time
     *
     * @param createTime the value for t_rebate_recd.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rebate_recd.update_time
     *
     * @return the value of t_rebate_recd.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rebate_recd.update_time
     *
     * @param updateTime the value for t_rebate_recd.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}