package com.tj.bet.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class UserTransactionRecd implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.id
     *
     * @mbg.generated
     */
    private Long id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.third_party_id
     *
     * @mbg.generated
     */
    private String thirdPartyId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.recd_type
     *
     * @mbg.generated
     */
    private Integer recdType;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.actual_amount
     *
     * @mbg.generated
     */
    private BigDecimal actualAmount;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.user_id
     *
     * @mbg.generated
     */
    private Integer userId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.version
     *
     * @mbg.generated
     */
    private Integer version;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.recd_status
     *
     * @mbg.generated
     */
    private Integer recdStatus;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.create_time
     *
     * @mbg.generated
     */
    private Date createTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.user_remark
     *
     * @mbg.generated
     */
    private String userRemark;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.sys_remark
     *
     * @mbg.generated
     */
    private String sysRemark;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.fee
     *
     * @mbg.generated
     */
    private BigDecimal fee;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.fee_ratio
     *
     * @mbg.generated
     */
    private BigDecimal feeRatio;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.audit_status
     *
     * @mbg.generated
     */
    private Integer auditStatus;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.audit_time
     *
     * @mbg.generated
     */
    private Date auditTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.audit_remark
     *
     * @mbg.generated
     */
    private String auditRemark;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.audit_user
     *
     * @mbg.generated
     */
    private Integer auditUser;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.platform
     *
     * @mbg.generated
     */
    private Integer platform;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.target_addr
     *
     * @mbg.generated
     */
    private String targetAddr;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_transaction_recd.snapshot
     *
     * @mbg.generated
     */
    private String snapshot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.id
     *
     * @return the value of t_user_transaction_recd.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.id
     *
     * @param id the value for t_user_transaction_recd.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.third_party_id
     *
     * @return the value of t_user_transaction_recd.third_party_id
     *
     * @mbg.generated
     */
    public String getThirdPartyId() {
        return thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.third_party_id
     *
     * @param thirdPartyId the value for t_user_transaction_recd.third_party_id
     *
     * @mbg.generated
     */
    public void setThirdPartyId(String thirdPartyId) {
        this.thirdPartyId = thirdPartyId == null ? null : thirdPartyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.recd_type
     *
     * @return the value of t_user_transaction_recd.recd_type
     *
     * @mbg.generated
     */
    public Integer getRecdType() {
        return recdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.recd_type
     *
     * @param recdType the value for t_user_transaction_recd.recd_type
     *
     * @mbg.generated
     */
    public void setRecdType(Integer recdType) {
        this.recdType = recdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.amount
     *
     * @return the value of t_user_transaction_recd.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.amount
     *
     * @param amount the value for t_user_transaction_recd.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.actual_amount
     *
     * @return the value of t_user_transaction_recd.actual_amount
     *
     * @mbg.generated
     */
    public BigDecimal getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.actual_amount
     *
     * @param actualAmount the value for t_user_transaction_recd.actual_amount
     *
     * @mbg.generated
     */
    public void setActualAmount(BigDecimal actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.user_id
     *
     * @return the value of t_user_transaction_recd.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.user_id
     *
     * @param userId the value for t_user_transaction_recd.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.version
     *
     * @return the value of t_user_transaction_recd.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.version
     *
     * @param version the value for t_user_transaction_recd.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.recd_status
     *
     * @return the value of t_user_transaction_recd.recd_status
     *
     * @mbg.generated
     */
    public Integer getRecdStatus() {
        return recdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.recd_status
     *
     * @param recdStatus the value for t_user_transaction_recd.recd_status
     *
     * @mbg.generated
     */
    public void setRecdStatus(Integer recdStatus) {
        this.recdStatus = recdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.update_time
     *
     * @return the value of t_user_transaction_recd.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.update_time
     *
     * @param updateTime the value for t_user_transaction_recd.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.create_time
     *
     * @return the value of t_user_transaction_recd.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.create_time
     *
     * @param createTime the value for t_user_transaction_recd.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.user_remark
     *
     * @return the value of t_user_transaction_recd.user_remark
     *
     * @mbg.generated
     */
    public String getUserRemark() {
        return userRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.user_remark
     *
     * @param userRemark the value for t_user_transaction_recd.user_remark
     *
     * @mbg.generated
     */
    public void setUserRemark(String userRemark) {
        this.userRemark = userRemark == null ? null : userRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.sys_remark
     *
     * @return the value of t_user_transaction_recd.sys_remark
     *
     * @mbg.generated
     */
    public String getSysRemark() {
        return sysRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.sys_remark
     *
     * @param sysRemark the value for t_user_transaction_recd.sys_remark
     *
     * @mbg.generated
     */
    public void setSysRemark(String sysRemark) {
        this.sysRemark = sysRemark == null ? null : sysRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.fee
     *
     * @return the value of t_user_transaction_recd.fee
     *
     * @mbg.generated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.fee
     *
     * @param fee the value for t_user_transaction_recd.fee
     *
     * @mbg.generated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.fee_ratio
     *
     * @return the value of t_user_transaction_recd.fee_ratio
     *
     * @mbg.generated
     */
    public BigDecimal getFeeRatio() {
        return feeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.fee_ratio
     *
     * @param feeRatio the value for t_user_transaction_recd.fee_ratio
     *
     * @mbg.generated
     */
    public void setFeeRatio(BigDecimal feeRatio) {
        this.feeRatio = feeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.audit_status
     *
     * @return the value of t_user_transaction_recd.audit_status
     *
     * @mbg.generated
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.audit_status
     *
     * @param auditStatus the value for t_user_transaction_recd.audit_status
     *
     * @mbg.generated
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.audit_time
     *
     * @return the value of t_user_transaction_recd.audit_time
     *
     * @mbg.generated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.audit_time
     *
     * @param auditTime the value for t_user_transaction_recd.audit_time
     *
     * @mbg.generated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.audit_remark
     *
     * @return the value of t_user_transaction_recd.audit_remark
     *
     * @mbg.generated
     */
    public String getAuditRemark() {
        return auditRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.audit_remark
     *
     * @param auditRemark the value for t_user_transaction_recd.audit_remark
     *
     * @mbg.generated
     */
    public void setAuditRemark(String auditRemark) {
        this.auditRemark = auditRemark == null ? null : auditRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.audit_user
     *
     * @return the value of t_user_transaction_recd.audit_user
     *
     * @mbg.generated
     */
    public Integer getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.audit_user
     *
     * @param auditUser the value for t_user_transaction_recd.audit_user
     *
     * @mbg.generated
     */
    public void setAuditUser(Integer auditUser) {
        this.auditUser = auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.platform
     *
     * @return the value of t_user_transaction_recd.platform
     *
     * @mbg.generated
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.platform
     *
     * @param platform the value for t_user_transaction_recd.platform
     *
     * @mbg.generated
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.target_addr
     *
     * @return the value of t_user_transaction_recd.target_addr
     *
     * @mbg.generated
     */
    public String getTargetAddr() {
        return targetAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.target_addr
     *
     * @param targetAddr the value for t_user_transaction_recd.target_addr
     *
     * @mbg.generated
     */
    public void setTargetAddr(String targetAddr) {
        this.targetAddr = targetAddr == null ? null : targetAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_transaction_recd.snapshot
     *
     * @return the value of t_user_transaction_recd.snapshot
     *
     * @mbg.generated
     */
    public String getSnapshot() {
        return snapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_transaction_recd.snapshot
     *
     * @param snapshot the value for t_user_transaction_recd.snapshot
     * @mbg.generated
     */
    public void setSnapshot(String snapshot) {
        this.snapshot = snapshot == null ? null : snapshot.trim();
    }
}