package com.tj.task.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class UserBalanceInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_balance_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance_info.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance_info.version
     *
     * @mbg.generated
     */
    private Integer version;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance_info.freazon_amount
     *
     * @mbg.generated
     */
    private BigDecimal freazonAmount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_balance_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance_info.user_id
     *
     * @return the value of t_user_balance_info.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance_info.user_id
     *
     * @param userId the value for t_user_balance_info.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance_info.amount
     *
     * @return the value of t_user_balance_info.amount
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance_info.amount
     *
     * @param amount the value for t_user_balance_info.amount
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance_info.version
     *
     * @return the value of t_user_balance_info.version
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance_info.version
     *
     * @param version the value for t_user_balance_info.version
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance_info.freazon_amount
     *
     * @return the value of t_user_balance_info.freazon_amount
     * @mbg.generated
     */
    public BigDecimal getFreazonAmount() {
        return freazonAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance_info.freazon_amount
     *
     * @param freazonAmount the value for t_user_balance_info.freazon_amount
     * @mbg.generated
     */
    public void setFreazonAmount(BigDecimal freazonAmount) {
        this.freazonAmount = freazonAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance_info.update_time
     *
     * @return the value of t_user_balance_info.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance_info.update_time
     *
     * @param updateTime the value for t_user_balance_info.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_balance_info.create_time
     *
     * @return the value of t_user_balance_info.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_balance_info.create_time
     *
     * @param createTime the value for t_user_balance_info.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}