package com.tj.task.dao;

import com.tj.task.domain.UserTransactionRecd;
import com.tj.task.domain.UserTransactionRecdExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface UserTransactionRecdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    long countByExample(UserTransactionRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    int deleteByExample(UserTransactionRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    int insert(UserTransactionRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    int insertSelective(UserTransactionRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    List<UserTransactionRecd> selectByExampleWithRowbounds(UserTransactionRecdExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    List<UserTransactionRecd> selectByExample(UserTransactionRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    UserTransactionRecd selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserTransactionRecd record, @Param("example") UserTransactionRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserTransactionRecd record, @Param("example") UserTransactionRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserTransactionRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_transaction_recd
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserTransactionRecd record);
}