package com.tj.task.dao;

import com.tj.task.domain.UserBalanceChangeRecd;
import com.tj.task.domain.UserBalanceChangeRecdExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface UserBalanceChangeRecdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    long countByExample(UserBalanceChangeRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    int deleteByExample(UserBalanceChangeRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    int insert(UserBalanceChangeRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    int insertSelective(UserBalanceChangeRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    List<UserBalanceChangeRecd> selectByExampleWithRowbounds(UserBalanceChangeRecdExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    List<UserBalanceChangeRecd> selectByExample(UserBalanceChangeRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    UserBalanceChangeRecd selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserBalanceChangeRecd record, @Param("example") UserBalanceChangeRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserBalanceChangeRecd record, @Param("example") UserBalanceChangeRecdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserBalanceChangeRecd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_balance_change_recd
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBalanceChangeRecd record);
}