package com.tj.event.dao;

import com.tj.event.domain.CategoryMapping;
import com.tj.event.domain.CategoryMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CategoryMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    long countByExample(CategoryMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    int deleteByExample(CategoryMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    int insert(CategoryMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    int insertSelective(CategoryMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    List<CategoryMapping> selectByExampleWithRowbounds(CategoryMappingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    List<CategoryMapping> selectByExample(CategoryMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    CategoryMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CategoryMapping record, @Param("example") CategoryMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CategoryMapping record, @Param("example") CategoryMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CategoryMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CategoryMapping record);
}