package com.tj.event.dao;

import com.tj.event.domain.TeamMapping;
import com.tj.event.domain.TeamMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TeamMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    long countByExample(TeamMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    int deleteByExample(TeamMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    int insert(TeamMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    int insertSelective(TeamMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    List<TeamMapping> selectByExampleWithBLOBsWithRowbounds(TeamMappingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    List<TeamMapping> selectByExampleWithBLOBs(TeamMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    List<TeamMapping> selectByExampleWithRowbounds(TeamMappingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    List<TeamMapping> selectByExample(TeamMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    TeamMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TeamMapping record, @Param("example") TeamMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TeamMapping record, @Param("example") TeamMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TeamMapping record, @Param("example") TeamMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeamMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TeamMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeamMapping record);
}